const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const RegressionReporter =
    require('../report/RegressionReporter');

class PrCommenter {

    static isAvailable() {

        try {
            execSync('gh --version', { stdio: 'pipe' });
            return true;
        } catch {
            return false;
        }
    }

    static buildComment(report) {

        const impact =
            report.impact || {};

        const execution =
            report.execution || {};

        const scenarios =
            report.generation?.domains
                ?.flatMap(domain =>
                    domain.scenarios
                        ? Object.entries(domain.scenarios)
                            .map(([layer, summary]) =>
                                `- **${domain.domain}.${layer}**: ${summary.positive} pos / ${summary.negative} neg / ${summary.edge} edge`
                            )
                        : []
                ) || [];

        const diffSignals =
            report.diffAnalysis?.signals?.join(', ')
            || 'n/a';

        const statusEmoji =
            !execution.executed
                ? '🔍'
                : execution.passed
                    ? '✅'
                    : '❌';

        const lines = [
            '## 🤖 Regression Agent Report',
            '',
            `${statusEmoji} **Status:** ${
                !execution.executed
                    ? 'Analysis only'
                    : execution.passed
                        ? 'PASSED'
                        : 'FAILED'
            }`,
            '',
            `**Trigger:** ${report.trigger || 'n/a'}`,
            `**Domains:** ${(impact.domains || []).join(', ') || 'none'}`,
            `**Diff signals:** ${diffSignals}`,
            `**Tests run:** ${(report.tests || []).length}`,
            ''
        ];

        if (scenarios.length > 0) {
            lines.push('### Generated Scenarios');
            lines.push(...scenarios);
            lines.push('');
        }

        if (execution.executed) {
            lines.push(
                `**Duration:** ${((execution.durationMs || 0) / 1000).toFixed(1)}s`
            );
            lines.push('');
        }

        lines.push('### Selected Tests');
        for (const test of (report.tests || []).slice(0, 12)) {
            lines.push(`- \`${test}\``);
        }

        if ((report.tests || []).length > 12) {
            lines.push(
                `- ...and ${report.tests.length - 12} more`
            );
        }

        lines.push('');
        lines.push(
            '_Generated by Regression Agent — Phase 5_'
        );

        return lines.join('\n');
    }

    static postComment(report, options = {}) {

        const prNumber =
            options.prNumber
            || report.pr?.prNumber;

        if (!prNumber) {
            return {
                posted: false,
                reason: 'No PR number provided'
            };
        }

        if (!this.isAvailable()) {
            return {
                posted: false,
                reason: 'gh CLI not available'
            };
        }

        const repo =
            options.repo
            || report.pr?.repo
            || process.env.GITHUB_REPO
            || process.env.GITHUB_REPOSITORY;

        const rootDir =
            options.rootDir || process.cwd();

        const body =
            options.body
            || this.buildComment(report);

        const tempFile =
            path.join(
                rootDir,
                '.cache/pr-comment.md'
            );

        fs.mkdirSync(
            path.dirname(tempFile),
            { recursive: true }
        );

        fs.writeFileSync(tempFile, body);

        try {

            execSync(
                `gh pr comment ${prNumber} --repo ${repo} --body-file "${tempFile}"`,
                {
                    cwd: rootDir,
                    stdio: 'pipe'
                }
            );

            return {
                posted: true,
                prNumber,
                repo,
                body
            };

        } catch (error) {

            return {
                posted: false,
                prNumber,
                repo,
                error: error.message
            };
        }
    }
}

module.exports = PrCommenter;
